version: "2"
linters:
  enable:
    - staticcheck
    - errcheck
    - govet
    - copyloopvar
    - misspell
    - durationcheck
    - predeclared
    - sloglint
    - lll
formatters:
  enable:
    - gofmt
