# yaml-language-server: $schema=https://raw.githubusercontent.com/wtnb75/gilterweb/refs/heads/main/schema.json

server:
  network: tcp
  addr: ":8888"

filters:
  - id: A
    type: http
    params:
      method: GET
      url: https://httpbin.org/ip
  - id: B
    type: static
    params: "hello {{.A.body.origin}}"

log:
  level: info
  format: json

paths:
  - method: GET
    path: /foo
    filter: B
